### ISSUE TITLE
Save image don't work

### ISSUE THREAD

**Issue by jmsong2** [ConstantinoSchillebeeckx/phylogram_d3#40]
Hi,

     The button of 'save image' is not working, even thought the demo http://constantinoschillebeeckx.github.io/phylogram_d3/. 
And the Chrome brower returned a error information "Uncaught DOMException: Failed to read the 'rules' property from 'CSSStyleSheet': Cannot access rules at HTMLButtonElement.saveSVG (https://cdn.rawgit.com/ConstantinoSchillebeeckx/phylogram_d3/9bc07b2c/js/utils.js:1139:31)    at HTMLButtonElement.__onclick (https://d3js.org/d3.v3.min.js:1:5253)" .
   Look forward to your help. Thank you.

Regards,
Jiaming

**Comment by ConstantinoSchillebeeckxSimpleRose** [comment]
Are you by chance using Chrome? It looks like Chrome is now [enforcing CORS policy](https://stackoverflow.com/a/49160760/1153897) for stylesheets which is the issue here.

This project is a bit old and isn't being maintained anymore.
